//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact2015.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contacts2015Entities : DbContext
    {
        public Contacts2015Entities()
            : base("name=Contacts2015Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<contact> contacts { get; set; }
        public DbSet<country> countries { get; set; }
        public DbSet<forgotPass> forgotPasses { get; set; }
        public DbSet<user> users { get; set; }
    }
}
